---
- hosts: bastion
  tasks:
  - name: make NetworkManager keep out of DNS
    ini_file:
      path: /etc/NetworkManager/NetworkManager.conf
      state: present
      no_extra_spaces: yes
      section: main
      option: dns
      value: none
      owner: root
      group: root
      mode: 0644
      backup: yes
    
  - name: deploy resolv.conf template
    template:
      src: templates/resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: deploy rhel-satellite.sh script
    template:
      src: templates/rhel_satellite.sh.j2
      dest: /usr/local/bin/rhel_satellite.sh 
      owner: root
      group: root
      mode: 0755
      backup: yes

  - name: run rhel-satellite.sh script
    command: /usr/local/bin/rhel_satellite.sh
    become: yes
 
  - name: deploy stage2-containers.sh script
    template:
      src: templates/stage2-containers.sh.j2
      dest: /usr/local/bin/stage2-containers.sh
      owner: root
      group: root
      mode: 0755
      backup: yes

  - name: Create unit file for stage2-containers.service
    copy:
      content: "[Unit]\nAfter=console-login-helper-messages-issuegen.service\n[Service]\nType=oneshot\nExecStart=/usr/local/bin/stage2-containers.sh\n[Install]\nWantedBy=multi-user.target\n"
      dest: /etc/systemd/system/stage2-containers.service
      owner: root
      group: root
      mode: 0644


