- hosts: svcs, asvcs, csvcs, esvcs
  serial: 1
  vars:
    Dig_target: ""  # Add a point which the network can lookup to
  max_fail_percentage: 0

  tasks: 
    - name: "DNS Dig"
      shell: dig {{ Dig_target }} @{{ item }} 
      register: task_result
      until: task_result.rc == 0
      retries: 10
      delay: 1

    - name: Check status of CoreDNS   
      command: systemctl status {{ item }}
      register: result
      with_items:
        - coredns

    - name: Fail Query
      fail: msg="Service on {{ item }}"
      when: result != "running"

    - name: "Updating"
      yum:
        name: '*'
        state: latest
        register: task_result
        until: task_result.rc == 0
        retries: 10
        delay: 1
        
    - name: Reboot
      reboot:
      
    - name: "sleep"
      wait_for:
      timeout: 10

    - name: "DNS Dig"
      shell: dig {{ Dig_target }} @{{ item }} 
      register: task_result
      until: task_result.rc == 0
      retries: 10
      delay: 1

    - name: Check status of CoreDNS   
      command: systemctl status {{ item }}
      register: result
      with_items:
        - coredns

    - name: Fail Query
      fail: msg="Service on {{ item }}"
      when: result != "running"
