---
- hosts: localhost
  connection: local
  gather_facts: No
  tasks:
  - name: ensure ConsoleLink CRDs are present
    k8s:
      state: present
      definition: "{{ lookup('file', item) }}"
    with_fileglob:
    - "files/console-link-*.yml"
