- hosts: localhost
  tasks:
  - name: Create test sc
    k8s:
      state: present
      definition:
        allowVolumeExpansion: true
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: tier1
          namespace: ""
        parameters:
          availability: nova
          type: TIER1
        provisioner: kubernetes.io/cinder
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
