- hosts: localhost
  tasks:
 - name: Create sso secret
   command: oc create secret generic idp-secret --from-literal=clientSecret="{{ ssoSecret }}" -n openshift-config

  - name: Create OAuth resource
    k8s:
      state: present
      definition:
        apiVersion: config.openshift.io/v1
        kind: OAuth
        metadata: 
          name: cluster
        spec: 
          identityProviders: 
          - name: ukcloud-sso
            mappingMethod: claim 
            type: OpenID 
            openID: 
            clientID: "{{ ssoClientID }}"
            clientSecret: 
              name: idp-secret
            claims: 
              preferredUsername: 
              - preferred_username 
              name: 
              - name 
              email: 
              - email
            issuer: "{{ ssoIssuer }}"
     
    - name: Patch logout redirect into console
      command: oc patch Console cluster '{"spec":{"authentication":{"logoutRedirect":"{{ ssoLogoutURL }}"}}}
    
