---

- hosts: svcs, asvcs, csvcs, esvcs
  vars:
    ansible_ssh_user: root
    ansible_password: "{{ rhel_template_pw }}"
  tasks:
  - name: Create core user
    user:
      name: core
      groups: wheel append=yes 

  - name: Install public key to allow access
    authorized_key:
      user: core
      state: present
      key: "{{ ssh_pub_key }}"
