---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Configure DNS forwarding for specific zones
    k8s:
      state: present
      definition:
        apiVersion: operator.openshift.io/v1
        kind: DNS
        metadata:
          name: default
        spec:
          servers:
            "{{ dnsforwardingzones }}"
    when: dnsforwardingzones is defined and dnsforwardingzones|length != 0
