---
- hosts: localhost

  tasks:
  - name: Configure DNS forwarding for specific zones
    k8s:
      state: present
      definition:
        apiVersion: operator.openshift.io/v1
        kind: DNS
        metadata:
          name: default
        spec:
          servers:
            "{{ dnsforwardingzones }}"
    when: dnsforwardingzones is defined

  - name: Unconfigure DNS forwarding if necessary
    k8s:
      state: present
      definition:
        apiVersion: operator.openshift.io/v1
        kind: DNS
        metadata:
          name: default
        spec: {}
    when: dnsforwardingzones is not defined
