- hosts: localhost
  connection: local
  gather_facts: No
  tasks:
  - name: Create etcd-backup project
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          annotations:
            openshift.io/node-selector: ""
          name: etcd-backup

  - name: Create service account for etcd-backup
    k8s:
      state: present
      definition:
        kind: ServiceAccount
        apiVersion: v1
        metadata:
          name: openshift-backup
          namespace: etcd-backup
        labels:
          app: openshift-backup

  - name: Create cluster role for etcd-backup
    k8s:
      state: present
      definition:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: cluster-etcd-backup
        rules:
        - apiGroups: [""]
          resources:
            - "nodes"
          verbs: ["get", "list"]
        - apiGroups: [""]
          resources:
            - "pods"
            - "pods/log"
          verbs: ["get", "list", "create", "delete", "watch"]

  - name: Create cluster role binding for etcd-backup
    k8s:
      state: present
      definition:
        kind: ClusterRoleBinding
        apiVersion: rbac.authorization.k8s.io/v1
        metadata:
          name: openshift-backup
        labels:
          app: openshift-backup
        subjects:
          - kind: ServiceAccount
            name: openshift-backup
            namespace: etcd-backup
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-etcd-backup

  - name: Add privileged scc to openshift-backup service account
    command: oc adm policy add-scc-to-user privileged -z openshift-backup

  - name: Create backup cronjob
    k8s:
      state: present
      definition:
        kind: CronJob
        apiVersion: batch/v1beta1
        metadata:
          name: openshift-backup
          namespace: etcd-backup
        labels:
          app: openshift-backup
        spec:
          schedule: "55 1 * * *"
          concurrencyPolicy: Forbid
          successfulJobsHistoryLimit: 5
          failedJobsHistoryLimit: 5
          jobTemplate:
            metadata:
              labels:
                app: openshift-backup
            spec:
              backoffLimit: 0
              template:
                metadata:
                  labels:
                    app: openshift-backup
                spec:
                  containers:
                  - name: backup
                    image: "registry.redhat.io/openshift4/ose-cli"
                    command:
                    - "/bin/bash"
                    - "-c"
                    - oc get no -l node-role.kubernetes.io/master --no-headers -o name | xargs -I {} --  oc debug {} -- bash -c 'chroot /host sudo -E /usr/local/bin/cluster-backup.sh /home/core/backup/ && chroot /host sudo -E find /home/core/backup/ -type f -mtime +"4" -delete'
                  restartPolicy: Never
                  securityContext:
                    runAsUser: 1000670000
                    privileged: true
                  terminationGracePeriodSeconds: 30
                  activeDeadlineSeconds: 500
                  dnsPolicy: ClusterFirst
                  serviceAccountName: openshift-backup
                  serviceAccount: openshift-backup
