---
- hosts: localhost
  
  vars:
    infraMachineSetScale: 2

  tasks:
  - name: Wait for infra nodes to exist
    k8s_info:
      kind: Node
      label_selectors:
        - node-role.kubernetes.io/infra =
    register: infraNodeStatus
    until:
      - infraNodeStatus.resources | length == infraMachineSetScale
    retries: 60
    delay: 10

  - name: Schedule default ingresscontroller pods to infra nodes and enable logging
    k8s:
      state: present
      definition:
        apiVersion: operator.openshift.io/v1
        kind: IngressController
        metadata:
          name: default
          namespace: openshift-ingress-operator
        spec:
          logging:
            access:
              destination:
                type: Container
          nodePlacement:
            tolerations:
              - effect: NoSchedule 
                key: node-role.kubernetes.io/infra 
                operator: Exists
            nodeSelector:
              matchLabels:
                node-role.kubernetes.io/infra: ""

  - name: Schedule registry to infra nodes
    k8s:
      state: present
      definition:
        apiVersion: imageregistry.operator.openshift.io/v1
        kind: Config
        metadata:
          name: cluster
        spec:
          nodeSelector:
            node-role.kubernetes.io/infra: ""
          tolerations:
            - effect: NoSchedule 
              key: node-role.kubernetes.io/infra 
              operator: Exists

  - name: Create cluster-monitoring configmap
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: cluster-monitoring-config
          namespace: openshift-monitoring
        data:
          config.yaml: |+
            alertmanagerMain:
              nodeSelector:
                node-role.kubernetes.io/infra: ""
              tolerations:
                - effect: NoSchedule 
                  key: node-role.kubernetes.io/infra 
                  operator: Exists
            prometheusK8s:
              nodeSelector:
                node-role.kubernetes.io/infra: ""
              tolerations:
                - effect: NoSchedule 
                  key: node-role.kubernetes.io/infra 
                  operator: Exists
              retention: 7d
            prometheusOperator:
              nodeSelector:
                node-role.kubernetes.io/infra: ""
              tolerations:
                - effect: NoSchedule 
                  key: node-role.kubernetes.io/infra 
                  operator: Exists
            grafana:
              nodeSelector:
                node-role.kubernetes.io/infra: ""
              tolerations:
                - effect: NoSchedule 
                  key: node-role.kubernetes.io/infra 
                  operator: Exists
            k8sPrometheusAdapter:
              nodeSelector:
                node-role.kubernetes.io/infra: ""
              tolerations:
                - effect: NoSchedule 
                  key: node-role.kubernetes.io/infra 
                  operator: Exists
            kubeStateMetrics:
              nodeSelector:
                node-role.kubernetes.io/infra: ""
              tolerations:
                - effect: NoSchedule 
                  key: node-role.kubernetes.io/infra 
                  operator: Exists
            telemeterClient:
              nodeSelector:
                node-role.kubernetes.io/infra: ""
              tolerations:
                - effect: NoSchedule 
                  key: node-role.kubernetes.io/infra 
                  operator: Exists
            openshiftStateMetrics:
              nodeSelector:
                node-role.kubernetes.io/infra: ""
              tolerations:
                - effect: NoSchedule 
                  key: node-role.kubernetes.io/infra 
                  operator: Exists
            enableUserWorkload: true

  - name: Create user-workload-monitoring configmap
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: user-workload-monitoring-config
          namespace: openshift-user-workload-monitoring
        data:
          config.yaml: |
            prometheusOperator:
              nodeSelector:
                node-role.kubernetes.io/infra: ""
              tolerations:
                - effect: NoSchedule 
                  key: node-role.kubernetes.io/infra 
                  operator: Exists
            prometheus:
              nodeSelector:
                node-role.kubernetes.io/infra: ""
              tolerations:
                - effect: NoSchedule 
                  key: node-role.kubernetes.io/infra 
                  operator: Exists
              retention: 7d
            thanosRuler:
              nodeSelector:
                node-role.kubernetes.io/infra: ""
              tolerations:
                - effect: NoSchedule 
                  key: node-role.kubernetes.io/infra 
                  operator: Exists
