---
- hosts: localhost

  vars:
    routes:
      - name: "console"
        namespace: "openshift-console"
      - name: "kibana"
        namespace: "openshift-logging"
      - name: "alertmanager-main"
        namespace: "openshift-monitoring"
      - name: "grafana"
        namespace: "openshift-monitoring"
      - name: "prometheus-k8s"
        namespace: "openshift-monitoring"
      - name: "thanos-querier"
        namespace: "openshift-monitoring"

  tasks:
    - name: Patch APIServer
      k8s:
        state: present
        definition:
          apiVersion: config.openshift.io/v1
          kind: APIServer
          metadata:
            name: cluster
          spec:
            servingCerts:
              namedCertificates:
              - names:
                - "api.{{ domainSuffix}}"
                servingCertificate:
                  name: api-certs

    - name: Patch IngressController
      k8s:
        state: present
        definition:
          apiVersion: operator.openshift.io/v1
          kind: IngressController
          metadata:
            name: default
            namespace: openshift-ingress-operator
          spec:
            defaultCertificate:
              name: ingress-certs

    - name: Enable HSTS on routes
      k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            annotations:
              haproxy.router.openshift.io/hsts_header: max-age=31536000
            name: "{{ item.name }}"
            namespace: "{{ item.namespace }}"
      with_items: "{{ routes }}"
      when: not staging | default(false) | bool
