---
- hosts: localhost
  tasks:
  - name: Create secret with s3 access key and secret key
    k8s:
      state: present
      definition:
        apiVersion: v1
        data:
          REGISTRY_STORAGE_S3_ACCESSKEY: "{{ accessKey | b64encode }}"
          REGISTRY_STORAGE_S3_SECRETKEY: "{{ secretKey | b64encode }}"
        kind: Secret
        metadata:
          name: image-registry-private-configuration-user
          namespace: openshift-image-registry
        type: Opaque

  - name: Patch s3 details into image registry and remove pvc config
    k8s:
      state: present
      definition:
        apiVersion: imageregistry.operator.openshift.io/v1
        kind: Config
        metadata:
          name: cluster
        spec:
          managementState: Managed
          storage:
            pvc:
            s3:
              bucket: "{{ bucketName }}"
              region: "us-east1"
              regionEndpoint: "{{ regionEndpoint }}"
