---
- hosts: localhost
  gather_facts: False
  tasks:
  - name: Check for legacy imageName var
    set_fact: 
      rhcosImage: "{{ imageName }}"
    when: rhcosImage is not defined

  - name: Set domainSuffix
    set_fact:
      domainSuffix: "{{ custID }}.{{ baseDomain }}"
    when: domainSuffix is not defined

- import_playbook: object-storage.yml
- import_playbook: infra.yml
- import_playbook: storage.yml
- import_playbook: net2-ntp.yml
  when: net2 | default(false) | bool
- import_playbook: logging.yml
  when: logging | bool  
- import_playbook: add-machine-sets.yml
  when: additionalFlavors is defined
- import_playbook: dns-forwarding.yml
- import_playbook: console-customization.yml
- import_playbook: sso.yml
  when: useSingleSignOn | default(true) | bool
- import_playbook: networkpolicy.yml
  when: isolateProjectsNetworkPolicy | default(true) | bool  
- import_playbook: monitoring-sa.yml
- import_playbook: acme-sa.yml
  when: useLetsEncryptCert | default(true) | bool
- import_playbook: etcd-backup.yml
- import_playbook: ingress/main.yml
  when: (extraGateway | default(false) | bool) or (net2 | default(false) | bool)
- import_playbook: net2-ingress/main.yml
  when: net2 | default(false) | bool
- import_playbook: eg-ingress/main.yml
  when: extraGateway | default(false) | bool
- import_playbook: ingress/letsencrypt.yml
  when: useLetsEncryptCert | default(true) | bool
- import_playbook: nodeport-loadbalancing-ingress/main.yaml
  when: nodePortLb | default(false) | bool
