---
- import_playbook: sso.yml
- import_playbook: object-storage.yml
- import_playbook: infra.yml
- import_playbook: storage.yml
- import_playbook: logging.yml
  when: logging
- import_playbook: dns-forwarding.yml
- import_playbook: console-customization.yml
