---
- name: Check for legacy imageName var
  set_fact: 
    rhcosImage: "{{ imageName }}"
  when: rhcosImage is not defined

- name: Set domainSuffix
  set_fact:
    domainSuffix: "{{ custID }}.{{ baseDomain }}"
  when: domainSuffix is not defined

- import_playbook: object-storage.yml
- import_playbook: infra.yml
- import_playbook: storage.yml
- import_playbook: logging.yml
  when: logging | bool  
- import_playbook: dns-forwarding.yml
- import_playbook: console-customization.yml
- import_playbook: sso.yml
  when: useSingleSignOn | default(true) | bool
- import_playbook: ingress.yml
  when: useLetsEncryptCert | default(true) | bool
- import_playbook: monitoring-sa.yml
- import_playbook: acme-sa.yml
  when: useLetsEncryptCert | default(true) | bool
