---
- hosts: localhost
  tasks:
  - name: Get cloud-provider-config ConfigMap
    k8s_info:
      kind: ConfigMap
      name: cloud-provider-config
      namespace: openshift-config
    register: cloudproviderconfigConfigMap

  - name: Get cloud-provider-config data
    set_fact:
      cloudproviderConfig: '{{ cloudproviderconfigConfigMap.resources[0].data.config }}'

  - name: Note in a fact whether cloud-provider-config will be changed
    set_fact:
      cloudproviderConfigchanged: true
    when: not cloudproviderConfig is search("ignore-volume-az")

  - name: Alter cloud-provider-config to include ignore-volume-az if it isnt there already
    k8s:
      state: present
      definition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: cloud-provider-config
          namespace: openshift-config
        data:
          config: |
            {{ cloudproviderConfig }}
            [BlockStorage]
            ignore-volume-az = yes
    when: not cloudproviderConfig is search("ignore-volume-az")


  - name: Unset default storage class from standard SC
    k8s:
      state: present
      definition:
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: standard
          annotations:
            storageclass.kubernetes.io/is-default-class: "false"

  - name: Create tier 1 SC
    k8s:
      state: present
      definition:
        allowVolumeExpansion: true
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: tier1
          annotations:
            storageclass.kubernetes.io/is-default-class: "false"
        parameters:
          availability: nova
          type: TIER1
        provisioner: kubernetes.io/cinder
        reclaimPolicy: Delete
        volumeBindingMode: Immediate

  - name: Create tier 2 SC and set as default
    k8s:
      state: present
      definition:
        allowVolumeExpansion: true
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: tier2
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
        parameters:
          availability: nova
          type: TIER2
        provisioner: kubernetes.io/cinder
        reclaimPolicy: Delete
        volumeBindingMode: Immediate

  - name: Remove image registry PVC created during IPI deployment
    k8s:
      state: absent
      definition:
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: image-registry-storage
          namespace: openshift-image-registry
