---

- hosts: localhost
  tasks:
  - name: Create /tmp/workingdir/dns/ directory
    file:
      path: /tmp/workingdir/dns/
      state: directory

  - name: Make a Zonefile
    template:
      src: templates/zonefile.j2
      dest: /tmp/workingdir/dns/{{ domain_suffix }}.zone

  - name: Make a Corefile config
    template:
      src: templates/Corefile.j2
      dest: /tmp/workingdir/dns/Corefile

  - name: Install Unit file for coredns.service
    template:
      src: templates/coredns.service.j2
      dest: /tmp/workingdir/dns/coredns.service


- hosts: svcs
  gather_facts: false
  tasks:
  - name: Remove cni net.d files to workaround bugzilla 1729603
    raw: sudo rm -f /etc/cni/net.d/100-crio-bridge.conf /etc/cni/net.d/200-loopback.conf

  - name: Create /etc/coredns directory
    raw: mkdir -p /etc/coredns

  - name: Push Zonefile
    raw: echo '{{ lookup('file', '/tmp/workingdir/dns/{{ domain_suffix }}.zone') }}' > /etc/coredns/{{ domain_suffix }}.zone

  - name: Push Corefile
    raw: echo "{{ lookup('file', '/tmp/workingdir/dns/Corefile') }}" > /etc/coredns/Corefile

  - name: Push Unit file
    raw: echo "{{ lookup('file', '/tmp/workingdir/dns/coredns.service') }}" > /etc/systemd/system/coredns.service

  - name: Pull CoreDNS container
    raw: podman pull docker.io/coredns/coredns

  - name: Flush firewall rules and Enable coredns.service
    raw: sudo systemctl stop coredns.service; sudo nft flush ruleset; sudo systemctl daemon-reload; sudo systemctl enable coredns.service; sudo systemctl start coredns.service
