---
- hosts: localhost
  connection: local

  vars:
    namespace: "net2-ingress"
    net2NetworkName: "{{ net2ExternalNetwork | lower }}"

  tasks:
  - name: "Create {{ namespace }} namespace"
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ namespace }}"

  - name: Create secret containing sa token
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: "net2-ingress-sa"
          namespace: "{{ namespace }}"
        data:
          token: "{{ net2IngressSaToken | b64encode }}"

  - name: Create ImageStream
    k8s:
      state: present
      definition:
        apiVersion: image.openshift.io/v1
        kind: ImageStream
        metadata:
          name: update-loadbalancer-members
          namespace: "{{ namespace }}"
        spec:
          lookupPolicy:
            local: true

  - name: Create BuildConfig
    k8s:
      state: present
      definition:
        apiVersion: build.openshift.io/v1
        kind: BuildConfig
        metadata:
          labels:
            build: update-loadbalancer-members
          name: update-loadbalancer-members
          namespace: "{{ namespace }}"
        spec:
          nodeSelector:
            node-role.kubernetes.io/infra:
          output:
            to:
              kind: ImageStreamTag
              name: update-loadbalancer-members:latest
          source:
            binary: {}
            type: Binary
          strategy:
            dockerStrategy: {}
            type: Docker

  - name: Run Docker build
    command: "oc start-build update-loadbalancer-members --from-dir . -F -n {{ namespace }}"
    args:
      chdir: "./build"
    register: buildStatus
    failed_when: "'Push successful' not in buildStatus.stdout_lines"

  - name: Delete BuildConfig
    k8s:
      state: absent
      definition:
        apiVersion: build.openshift.io/v1
        kind: BuildConfig
        metadata:
          name: update-loadbalancer-members
          namespace: "{{ namespace }}"

  - name: Create update-loadbalancer-members CronJob
    k8s:
      state: present
      definition: "{{ lookup('template', 'templates/cronjob-update-loadbalancer-members.j2') }}"

  - name: Create IngressController
    k8s:
      state: present
      definition:
        apiVersion: operator.openshift.io/v1
        kind: IngressController
        metadata:
          namespace: openshift-ingress-operator
          name: "{{ net2NetworkName | replace('_','-') }}"
        spec:
          domain: "{{ net2NetworkName | replace('_','-') }}.{{ domainSuffix }}"
          nodePlacement:
            nodeSelector:
              matchLabels:
                network: "{{ net2NetworkName }}"
          replicas: 2
          routeSelector:
            matchExpressions:
            - key: network
              operator: In
              values:
              - "{{ net2NetworkName }}"
